### ISSUE TITLE
Twinsからインポートを押すと全データ削除のダイアログが出てしまう

### ISSUE THREAD

**Issue by SIY1121** [twin-te/twinte-front#102]
## 概要
Twinsからインポートを押すと全データ削除のダイアログが出てしまう
## 再現手順
Twinsからインポートを押す
## 修正しないとどう困るか
ヤバい
## 原因
switchの中で `break;` が抜けてます
## 修正案
`break;` を挿入する

**Comment by SIY1121** [comment]
https://github.com/twin-te/twinte-front/blob/6a1a7897e5fd4eaef0ab166a1824584ee13072dd/src/components/def-nav.vue#L92-L103

**Comment by takonasu** [comment]
これ解決済みだよね？
