### ISSUE TITLE
TypeError: undefined at def-dialog-add.vue

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#106]
## 概要

検索画面でのエラー
原因不明

## 再現手順

「コミュニティ」で検索

## 修正案

原因を見つけて消す

**Comment by SIY1121** [comment]
いま確認してみたんだけど
detailsが空の講義（特別講義かなんかで開講日時がkdbに無い講義）があるのに対して
`details[0].module` で決め打ちしてるのが原因かと思われる
![image](https://user-images.githubusercontent.com/17082836/72947755-68d79800-3dc6-11ea-9c10-0f6559408b60.png)

**Comment by HikaruEgashira** [comment]
とりあえず || ''いれるやつしてる
