### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#117]
## 概要

どっかのNuxtプロジェクトみたいに、Docker使おうぜ

## 目的

どっかのサーバーとうまくつながった開発環境を整える

## 提案内容

どっかの`tokyo-metropolitan-gov/covid19`がシンプル
nodeを使わなくて済むぐらいの改善しかないが

**Comment by takonasu** [comment]
これdev環境をからまず構築していきたいと思う
