### ISSUE TITLE
iPhoneアプリの実行時Androidと同様に「設定」メニューを追加して欲しい

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#119]
## 概要
設定ボタン・共有ボタンが欲しい。
## 目的
iOSのネイティブアプリ版でも通知やスクショ機能（共有）を実装するため、
それに伴い設定画面が必要になったのでそれを発火する
## 提案内容
` window.webkit.messageHandlers.callbackHandler.postMessage('');  `
を実行することによって、iOS側の関数を呼び出すことができるので、この実行をお願いします。

サンプルとして、 ` takonasu/iPhoneSamle ` ブランチに実装例を置いておきました、、が、僕はtsわからないのと、このままだとAndroidも設定ボタンが出てしまうので、うまく処理してもらいたいです。
## タスク

- [ ] iPhone設定ボタンの追加
- [ ] （余力があれば）Android設定ボタンとの実装共通化(リファクタリング)

**Comment by HikaruEgashira** [comment]
@SIY1121 Androidでは window.webkit 存在する?

Androidと同じように型増やして、
```
if (window.webkit) ... 
``` 
でいいかな?

**Comment by SIY1121** [comment]
`window.任意の名前` にオブジェクトを挿入できるので
iOSと名前を共通化してもいいし別にしても良いかと

**Comment by takonasu** [comment]
iOSアプリの方で多少変更がありました。
iOSアプリの設定画面を呼び出す時
`window.webkit?.messageHandlers.iPhoneSettings.postMessage('');`
Share機能を呼び出す時
`window.webkit?.messageHandlers.Share.postMessage('');`

を実行するよう変更お願いします・・・
@HikaruEgashira

**Comment by takonasu** [comment]
Share機能を呼び出す時
`window.webkit?.messageHandlers.Share.postMessage('シェアする文章');`
にしてもらえるとシェアする文章を指定できます

**Comment by takonasu** [comment]
細かいけどshareがいいのかな、Shareがいいのかな・・・

**Comment by HikaruEgashira** [comment]
CaseStyle統一したほうがいいかもなって考えた

**Comment by SIY1121** [comment]
jsの命名規則に則るならshareな希ガス

**Comment by takonasu** [comment]
デスヨネ・・・shareにする？
@HikaruEgashira
