### ISSUE TITLE
全角英数字・小文字英字でも授業番号検索ができるように

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#132]
## 概要
タイトルの通りです
## 目的
Twitterの意見で小文字入力できないのか！という人が多かったため
## 提案内容
全角英数字・小文字英字でも授業番号検索ができるようにする

## 問題点
ただ単純に大文字英字に変換してしまうと授業名で検索をかけたとき「English」等で検索できなくなってしまう。

**Comment by HikaruEgashira** [comment]
サーバー側でしたほうがいいタスクやな
