### ISSUE TITLE
ブラウザ版で外部ページを別ウィンドウで開く

### ISSUE THREAD

**Issue by yuki-js** [twin-te/twinte-front#136]
## 概要

現状、ブラウザ版ではシラバスなどの外部ページを開くとき同一ウィンドウで開かれる。
シラバスなどのページは別ウィンドウで開くようにする

## 目的

シラバスなどを参照しやすくするため

## 提案内容

`location.href` で遷移していた部分を、環境に応じて遷移の仕方を切り替える関数に置換する。
ソーシャルログイン画面の遷移は変更しなくても良いと思われる

**Comment by HikaruEgashira** [comment]
ネイティブで別ウィンドウ開かない仕様にしていたから、ブラウザ版だけ開くみたいな仕様は考慮してなかったな。。
localtionハンドラーあたりをutilにつくっといてそこで環境に応じた処理するようにしておくと楽かも。

**Comment by yuki-js** [comment]
やりますのでとりあえずアサインお願いします。

**Comment by yuki-js** [comment]
マージありがとうございます！閉じます！
