### ISSUE TITLE
ログインボタンのデザインをオリジナルに変更する

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#142]
## 目的
Twitterのログインボタンの解像度はあまりよくないのと、ちょっと見た目が不格好
## 提案内容
たとえば、あるサイトでは
![image](https://user-images.githubusercontent.com/37821819/79679544-ad49c700-8241-11ea-9b74-7d33cb6ce7e4.png)
のようになっているのでおそらく変更しても大丈夫なんだと思われます・・・

**Comment by KanadeNishizawa** [comment]
Appleのガイドラインでは、ある程度のカスタマイズはできるようですが、ログインボタンの規定はgoogle,twitterに比べて結構厳しいみたいです(悲しい)
例えばオリジナルデザインを作るとして、現状の3つのログインボタン全部に統一感を持たせるレベルを目指す(=独自のカスタマイズの要素が強くなる)と、禁止事項に抵触しそうです(とても悲しい)
https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/

巷のサイトたちでも、見過ごされているだけで厳密には公式のガイドラインに違反しているものが溢れているので、一旦慎重に調べてから「見た目が不格好」問題を考えたい。
よって、一旦**新しいデザインは作らず、Twitterログインボタンの解像度問題だけ**解決する方向でいきたい。

**Comment by HosokawaR** [comment]
Googleも結構厳しいです。。。[参考](https://developers.google.com/identity/branding-guidelines?hl=ja)
逆にTwitterやFacebookはゆるゆるです。
ただpaddingとかを明確に規定してるのはGoogleだけなので、全部Googleに合わせるとかならアリかも？しれません。
![image](https://user-images.githubusercontent.com/45098934/96361163-596f5a80-115e-11eb-9ee8-0ee39344cf1b.png)

**Comment by KanadeNishizawa** [comment]
お、情報ありがとうございます！
確かにgoogleはpaddingさえ守れば良い感じにカスタマイズできそうなのでtwitterとか合わせたいですね。
残念ポイントとして、appleは文字部分も含めたあの四角いボタンを使わないといけない(角丸の加減やリンゴマークの位置は調整可能)っぽい？ので、色とかフォントとかが変更可能な他の2つと比べるとどうしても浮いちゃうのかなあと・・・。
