### ISSUE TITLE
講義の検索結果の開講日時の表示が不十分

### ISSUE THREAD

**Issue by SIY1121** [twin-te/twinte-front#145]
## 概要
春A月1,2の講義は`春A月1`
春AB火1の講義は`春A火1`
のように最初の一つしか検索結果に表示されないため、勘違いしてしまう人がいるので出来れば全部表示したい。

## 目的
twin:teのみで時間割を仮組する人がおり、その表示を頼りに追加しようとしたら、表示されていない開講日時と他の講義がかぶって追加できないことがあり、UXが悪い。

## タスク

- [ ] detailsの配列から表示する文字列を生成する

**Comment by HosokawaR** [comment]
こういう感じのものを作ったのですが、見ずらいでしょうか？
「秋AB金56」あたりはいいかんじに纏まっているのですが、「春B月2C水3」がちょっとわかりにくいかなとも思っています。
![image](https://user-images.githubusercontent.com/45098934/98434621-cef29900-2114-11eb-9216-cc9ff4688e84.png)

**Comment by HikaruEgashira** [comment]
情報量として100パーセント入ってそうな文字列にできてそうなのでよさそうに感じる。
PRお願いします:pray:
