### ISSUE TITLE
履修単位数を表示したい

### ISSUE THREAD

**Issue by SIY1121** [twin-te/twinte-front#150]
## 概要
ユーザーが本年度履修してる単位数を表示したい
## 目的
Twin:teで時間割を仮組をする際に便利

## タスク

- [ ] `/user-lectures?year=2020` を呼び出して履修授業の一覧を取得
- [ ] 取得したデータは配列になってるので各要素の creditsの合計値を出す
- [x] 表示する場所を決める

**Comment by HikaruEgashira** [comment]
memoの縦幅を削る感じで実装していいと思う
該当ファイルはapp-modal-detail.vue

**Comment by hayato24s** [comment]
これも早めにやりたいですね

**Comment by HosokawaR** [comment]
https://github.com/twin-te/twinte-front/pull/504 により解決
