### ISSUE TITLE
メニューに寄付者一覧へのリンクを

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#151]
## 概要
寄付していただいたので、リンクを表示する
## 目的
寄付者一覧へのページへのリンクを貼ることによって感謝の意を示す。
また、寄付者一覧ページに寄付ページへのリンクもあるので寄付してもらいやすくする。
リンクは
https://www.twinte.net/sponsorship/index.html
## 問題点
Appleの審査が通らなくなる可能性がある（その時はその時・・・）

**Comment by HikaruEgashira** [comment]
@KanadeNishizawa サイドメニューのデザイン作って:pray:

**Comment by KanadeNishizawa** [comment]
普通にサイドバーの一覧に足す感じで良さそう〜と思ったけど、メニューのコンテンツが増えすぎるのが不安ではある・・・。（負債丸投げだけど新verで何とかしたい）
