### ISSUE TITLE
Windows版Chromeにおいて科目詳細モーダルの✕ボタンにスクロールバーが重なっている

### ISSUE THREAD

**Issue by asagatto777** [twin-te/twinte-front#182]
## 概要
Windowsにおいて科目詳細モーダルの✕ボタンにスクロールバーが重なっている（添付画像参照）
![image](https://user-images.githubusercontent.com/17997951/94544713-88dd2680-0286-11eb-8027-1d533688e142.png)

## 再現手順
Windows版Chromeで科目詳細モーダルを開く。

## 原因
適切なpaddingが設定されていない？

## 修正案
paddingを大きくするとデザインが狂いそうなので科目名部分をスクロール可能領域から省くなどが適切か。

**Comment by KanadeNishizawa** [comment]
(@asagatto777 issue建てありがとうございます!)

**メモ**
- おそらく、端末のスクロールバー設定で「常に表示」を有効にしているか否かによって表示が変わってしまうやつ

- 「常に表示」でない環境(これだとスクロールが発生した際にスクロールバーが表示されてもとは異なる太さ、挙動になる)で実装していたのが原因

 >  科目名部分をスクロール可能領域から省く

 が一番スマートに解決できそう

(あとこれはアプリ全体で起こりうるので別issueにすべきかもだけど、スクロールバー設定に左右されないpadding設定もしたい)
