### ISSUE TITLE
Escキーで科目表示モーダルを閉じる

### ISSUE THREAD

**Issue by AsagaKosho** [twin-te/twinte-front#183]
## 概要
現在、✕ボタンまたはモーダル領域外のクリックでしか閉じられない科目表示モーダルをEscキーの操作で閉じられるようにする。
## 目的
UXの向上
## 提案内容
概要と同様
## タスク
- [ ] モーダルを閉じるスクリプトのトリガーにEscキーの押下を追加する

**Comment by HikaruEgashira** [comment]
`@keyup.esc` とかかな

**Comment by HikaruEgashira** [comment]
このタスク完了です。
11月には反映されると思います:+1::+1:
