### ISSUE TITLE
集中授業を表示したい

### ISSUE THREAD

**Issue by KanadeNishizawa** [twin-te/twinte-front#195]
## 概要
集中授業を表示する。
今まで要望をもらいつつも実現できていなかったが、とりあえずデザインを作った。
ので、実装できそうだったらお願いします。

## 目的
集中授業を参照・編集できるようにすること。

## 提案内容
**デザインデータ**
(スクショに収まっていないので、詳しくはリンク先を参照して欲しいです。)
<img width="931" alt="スクリーンショット 2020-10-15 20 26 40" src="https://user-images.githubusercontent.com/48097323/96117269-c8fa0580-0f24-11eb-87be-c707e15395a9.png">

リンク: https://www.figma.com/file/4WzrwrZKO8uiSyTQYgjrs8/App?node-id=208%3A2512

## 備考
・new componentとしてmodal_smallを誕生させたい。
・これまでのmodalはmodal_largeに改名したい。
・button_smallコンポーネントと、それに利用する新しい色変数$primary-bright-colorが誕生します。

**Comment by SIY1121** [comment]
バックエンドが改修必要なので
来年の大型アプデを目安に準備します〜

**Comment by KanadeNishizawa** [comment]
V3で別の形で実装されるので
