### ISSUE TITLE
pj-Twin:te V3

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#204]
## 概要

新しくします。
一年生でも作業できるようにタスクを分割していきます。
分担については必要であればミーティングを行いましょう。

## 目的

- デザインを新しくし、UXを向上させる。
- 履修登録のための機能を充実させる。
- KDB機能をつける

## 手順

ひとまず以下をベースとします。（パクリ）

1. 該当の Issue またはここで @HikaruEgashira に mention してください。また、Assigneesの追加もお願いします。
2. 出来上がったら、 Pull Request を発行し、resolve #n の形式で Issue 番号を指定した Pull Request を送ってください。
3. ~1週間程度でレビュアーがレビューするので、適宜打ち返してください。

### デザイン

担当 @KanadeNishizawa & other(追加していく)

- [ ] StoryBookの追加
- [ ] コンポネントの作成
- [ ] コンポネントの置き換え

### フロントエンド

担当 @HikaruEgashira & other(追加していく)

- [x] APIの型定義
- [x] APIAdapterの修正
- [ ] APIAdapterのモックの追加
- [x] VuexAdapterの修正
- [ ] VuexAdapterをテスト可能に
- [ ] UseCaseの修正
- [ ] UseCaseの追加
- [ ] Presenterにロジックを書く
- [ ] Dockerの作成

**Comment by HosokawaR** [comment]
色々わからないところもあるので、一度ミーティングをしたいです！

**Comment by KanadeNishizawa** [comment]
デザインデータ
https://www.figma.com/file/ofC6dBEU96Tp3IlrobCtlJ/App-next?node-id=0%3A1

端末別のデザインとレスポンシブ対応について
https://www.figma.com/file/ofC6dBEU96Tp3IlrobCtlJ/App-next?node-id=804%3A8287

**Comment by KanadeNishizawa** [comment]
デザインガイドライン
(ルールのドキュメントなのでフロント実装する人は目を通しておいてください、取り急ぎまとめたので追記修正するかも)

https://www.figma.com/file/9AuxhAd2TmWvqMvwzCfGWK/Design-%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3-%E5%AE%9F%E8%A3%85%E3%81%99%E3%82%8B%E4%BA%BA%E3%81%AF%E8%AA%AD%E3%82%93%E3%81%A7%E3%81%AD
