### ISSUE TITLE
詳細画面で戻るボタンを押すと現在の学期に飛ばされる

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#274]
現在の学期が秋Cだとして、春Aの詳細画面を見る→戻るボタンを押す、と秋Cの画面にとばされてしまう。

**Comment by hayato24s** [comment]
vuexでcurrentModuleを保持ですかね？
これ、今履修仮組みの時期なので早めにやったほうがいいと思います。

**Comment by HosokawaR** [comment]
vuex は全体にまたがる情報を保存する最終手段なので、router の param とか利用できるならしたいところ
こいうのとかどうだろう
https://forsmile.jp/vue/910/

**Comment by hayato24s** [comment]
その方法もいいとは思うけれど、sidebarとlabelでvuexを既に使っているから、使っちゃっていいと思う。
むしろ、モジュールの管理の方がこの二つよりもvuexで行われるべきだと思ってる。
その方法を使うんだったら、sidebarとかlabelとかじゃないかな？どう思う？

**Comment by HosokawaR** [comment]
そうやな よくよく考えたらどのページから飛んできても（例えばPCで直接そのURLに飛ぶなど）前回選択したモジュールの学期にいたら便利なので、Vuex をつかうといいと思う。
俺がさっき反対したのは、/index /index/:id の２コンポーントで共有するのに Vuex は大げさすぎると思ったため

**Comment by hayato24s** [comment]
なるほどね、規模感の問題か。
