### ISSUE TITLE
適切なエラーメッセージを作成する

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#295]
現状サーバから返ってきたエラーメッセージをそのままユーザに出力しています。分かりづらいので、サーバからはエラーコードを返してもらい、ユーザフレンドリーなエラーメッセージをフロント側で表示したいです。

**Comment by HosokawaR** [comment]
エラーメッセージはユーザに的確な行動を取らせるための重要な手段なので、早めに実装したいです。

**Comment by KanadeNishizawa** [comment]
@HosokawaR  具体的なエラーパターン列挙してもらうことってできますか?:thinking_higero:

**Comment by HosokawaR** [comment]
まずはバックエンド側でエラーコードを定義してもらい、それに対してフロント側で適切なエラーメッセージを書きます。
ですのでバックエンドのタスクが落ち着き次第になります。

**Comment by HosokawaR** [comment]
現状はサーバから帰ってくる Status コードを見て適切なエラーメッセージをユーザに表示する実装になっている。
エラーの種類もそこまで多くない（せいぜい未認証など）のでこれで十分と判断し、この Issue を閉じる。
