### ISSUE TITLE
フィードバック機能をつける

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#296]
現状ユーザからのフィードバック手段が Twiiter と HP の small chart しかないのでアプリ内にフィードバック手段を実装したいです。

項目は

- カテゴリ
  - バグ報告
  - お問い合わせ
  - 新機能の要望
  - その他
- スクリーンショットの添付（実装しない可能性あり）
  - これは任意項目
- 本文
- 返信用メールアドレス
  - お問い合わせの場合必須

**Comment by KanadeNishizawa** [comment]
@HosokawaR  これ、時期的には目安どれくらいで実装できそうでしょうか？
アプリ内にこの機能あるならwwwのsmallchatを消しても良さそうなので、wwwをスリム化するにあたって助かるなと思っており

**Comment by HosokawaR** [comment]
feedback 機能はもうすでに手元でうまく動いているのでとりあえず文字のみのやり取りでいいなら PR を打てます。今はスクリーンショットのファイル添付機能でもつけようかな、とのんびり実装していた感じです。
しかし www の件ですが、おそらく small chat 以外に原因があり、small chat を消してもあまり効果がなさそうです。

**Comment by KanadeNishizawa** [comment]
承知です、あざます!!(問い合わせ経路を乱立させたくないという意図もあった)
