### ISSUE TITLE
ログアウトの確認　授業名・教室変更　手動授業追加　

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#30]
## 目的
間違えてログアウトする可能性がある。
その他はユーザーの要望。
## 提案内容
- ログアウトする際に確認のダイアログを出すと良い
- 授業名や教室名を自由に変更できると良い
- 手動で授業を追加したい人もいるようなので対応できると良い

**Comment by HikaruEgashira** [comment]
変更、個別追加はUIができたら、追加します。
確認はdetailブランチで行います
