### ISSUE TITLE
Cannot read property 'filter' of undefined と表示される

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#301]
![image](https://user-images.githubusercontent.com/45098934/113336107-d5520d80-9360-11eb-9d3b-5f48daa8fce7.png)

## 再現手順
1. 授業検索
2. すでに時間割に追加している授業を選択
3.  「指定された講義は既に登録されています」のエラーが表示される
4. もどるボタンを押すとスクリーンショットのようになる

**Comment by HosokawaR** [comment]
発見時の dev が最新版ではない可能性があり、最新のコミットでは修正されているかもしれません。

**Comment by hayato24s** [comment]
app.twinte.netで結構みるのですが、どこが原因かわかりますか？

**Comment by HikaruEgashira** [comment]
これ治ってる可能性がある ref #343

**Comment by HosokawaR** [comment]
経過観察状態でしたが、半年経過したので閉じます。
問題が再度発生したらまｔ開きます。
