### ISSUE TITLE
授業をいっぱい追加したいときにステップが多すぎる

### ISSUE THREAD

**Issue by takonomura** [twin-te/twinte-front#302]
科目を追加するときは

1. サイドバーの「授業を追加」をクリック
2. 「授業を検索」をクリック
3. 科目名等を入力
4. 登録したい科目にチェックを入れる
5. 「選択した授業を追加」をクリック

とステップが多くマウスの移動距離も長いので、1授業であればいいがたくさんの授業を入れたいときはストレスになってしまう
検索画面でチェックのついた授業を貯めておくことができるようになれば

1. サイドバーの「授業を追加」をクリック
2. 「授業を検索」をクリック
3. 1つ目の科目名等を入力
4. 登録したい科目にチェックを入れる
5. 2つ目の科目名等を入力
6. 登録したい科目にチェックを入れる
7. 「選択した授業を追加」をクリック

のように最初からやり直す必要がなくて効率的で嬉しい

**Comment by HosokawaR** [comment]
個人的に欲しい機能です。スマホ版のスペース、UIの複雑化が難点です。ただやはり現状のままだと使いにくさがあるので

1. PC版のみこの機能を実施する
履修登録だけpcで行う人も多いいのではないのでしょうか。その場合これは検討する余地ありです。

2. そもそも追加した後リダイレクトしない
講義を追加する場合はまとめて行うことが多いので、毎回時間割にリダイレクトするのは返ってユーザ体験を損なっているかもしれません。

**Comment by hayato24s** [comment]
重複モーダルのような感じで追加する科目のモーダルを表示するのはどうでしょう？
追加モーダル -> 重複モーダル
の順で、
これだと逆に一個しか授業を追加しないときにうざいですかね？

**Comment by HosokawaR** [comment]
何を追加したのか途中で忘れてしまうので、追加途中で確認できる機能が必要かと思います。その確認手段としてモーダルを用いるのはいいかもしれません。

**Comment by HosokawaR** [comment]
https://github.com/twin-te/twinte-front/pull/516 で解決
