### ISSUE TITLE
Source Map が欲しい

### ISSUE THREAD

**Issue by takonomura** [twin-te/twinte-front#306]
#305 を見つけたときに、エラーメッセージの情報があまりにも少なくわからなかったので、 production でも Source Map があると便利そうです

**Comment by HosokawaR** [comment]
Dev, local では source map を有効したほうがいいですね。ユーザにコンパイル前のコードを見られるのはちょっと気持ち悪さがあるので、Production では source map をオフにし、代わりに sentry などのエラー検知ツールに source map をアップロードしてそこで対応したいです。

**Comment by takonomura** [comment]
OSS なのでユーザーもコンパイル前のコード見られるので何も問題がないかと

**Comment by HosokawaR** [comment]
そういえば twinte は OSS でした。なら問題なさそうです。
