### ISSUE TITLE
授業形式が表示されない

### ISSUE THREAD

**Issue by takonomura** [twin-te/twinte-front#307]
科目詳細ページ (`/course/{id}`)で授業形式が必ず `-` になっている。編集ページに行くと選択されているので表示の問題だと思います。

**Comment by HikaruEgashira** [comment]
配列なのでundefined分岐が入ってる。
詳細編集画面で保存すると授業形式は表示されるし、逆に教室は消える😂

**Comment by hayato24s** [comment]
これってどなたか対応していますか？

**Comment by HosokawaR** [comment]
僕もしてないのでだれもしてないかと
