### ISSUE TITLE
授業検索時にローディングを

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#311]
検索できてるのか分からない時があったのでローディングが表示されると分かりやすいなと思った

**Comment by HosokawaR** [comment]
ローディング中にボタンが押されるのを防止するために、ボタンにローディングアニメーションを付けたいです。そうすればローディングと２重送信の両方が防げます。

**Comment by HosokawaR** [comment]
ログを見ていると、複数回同じワードで検索している人が目立ちます。おそらく反応がないと思って何回かボタンを押している or Enter の後に検索ボタンを押しているのだと思われます。

**Comment by HosokawaR** [comment]
@KanadeNishizawa 

> ボタンにローディングアニメーションを付けたいです。

ボタンにつけるローディングに希望があれば教えていただきたいです。
例えばこの中から選んでいただけると
https://projects.lukehaas.me/css-loaders/
https://connoratherton.com/loaders

イメージとしては、検索時に検索ボタンの虫眼鏡アイコンがローディングアイコンに変わり、ボタンは disable 状態になるような感じです。

**Comment by KanadeNishizawa** [comment]
@HosokawaR 
提示してくれた候補の中だと、1つ目のリンクの上段右端のものがいいなって思いました!

**Comment by HosokawaR** [comment]
@KanadeNishizawa 

これで間違いないでしょうか。
画面サイズによって「上段右端」が異なるため念の為確認させていただきました。
![image](https://user-images.githubusercontent.com/45098934/161011587-72b290e4-ac5f-4475-92bc-c2e0907f1e60.png)

**Comment by KanadeNishizawa** [comment]
@HosokawaR  おっと失礼しました…確認あざます、それです!!
