### ISSUE TITLE
画面サイズによってはサイドバーにアクセスできない

### ISSUE THREAD

**Issue by takonomura** [twin-te/twinte-front#314]
縦幅が一定より小さく、かつ横幅が一定より大きい画面サイズにおいてサイドバーが表示されず、左上のボタンも無いのでメニューにアクセスする方法が無くなってしまう

**Comment by hayato24s** [comment]
@KanadeNishizawa @HikaruEgashira 
パソコン画面でサイドバーが表示されないことがあり、授業追加などの機能が使えず詰んでしまいます。（少なくとも僕のパソコンはそうでした。）
早めに対応した方がいいと思います。
```
$pc-and-tab-height: 860px;
$pc-and-tab-width: 429px;
```

**Comment by HosokawaR** [comment]
#328 によって解決

**Comment by KanadeNishizawa** [comment]
修正ありがとうございました!
ちょっと正しいレイアウトによる解決でなかった&メニューが閉じられないbugが新たに発生したのでReopenしますね

**Comment by KanadeNishizawa** [comment]
具体的には
- PCレイアウト(サイドバーが常に表示&左上のメニューボタンは非表示)になるべきスクリーンサイズで、左上のメニューボタンからしかメニューが開けない状態
- 開いたメニューが閉じられず、背景のblurがかからない
