### ISSUE TITLE
空きコマをタップしたら授業検索に遷移してほしい

### ISSUE THREAD

**Issue by smasato** [twin-te/twinte-front#330]
ホームの空きコマをタップしたらタップ元コマの学期・曜日・時限がセットされた状態の授業検索ページに遷移すると直感的な気がする

**Comment by HikaruEgashira** [comment]
とても良さそうですね！
開発者側への要件提案ですが、検索クエリとパスが双方向バインディングされるようにしておくとこういった検索に便利かと思います
