### ISSUE TITLE
index.vue で授業場所が複数ある場合折り返されない

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#331]
授業名が長くなるとスクロールする

**Comment by hayato24s** [comment]
<img width="365" alt="スクリーンショット 2021-04-03 15 09 33" src="https://user-images.githubusercontent.com/68944024/113470250-1ba58a80-948f-11eb-89b3-f6b3caa52e48.png">

**Comment by hayato24s** [comment]
roomってバックエンドの方で`,`で結合していたんですか？
@SIY1121 

<img width="520" alt="スクリーンショット 2021-04-03 17 17 44" src="https://user-images.githubusercontent.com/68944024/113472832-9e831100-94a0-11eb-9e47-4a1c7ea1f7a9.png">

**Comment by SIY1121** [comment]
バックエンドでは特に処理してません

**Comment by hayato24s** [comment]
これ、間の空白の正体が改行文字になっているという解釈であっていますかね？

**Comment by hayato24s** [comment]
<img width="378" alt="スクリーンショット 2021-04-03 17 40 05" src="https://user-images.githubusercontent.com/68944024/113473280-ad1ef780-94a3-11eb-979b-daf4d3646846.png">
