### ISSUE TITLE
iOS Appでメモ欄の枠のstyleが消えている

### ISSUE THREAD

**Issue by KanadeNishizawa** [twin-te/twinte-front#338]
MacOS Safariでは正常に表示されているが、safariが適用されるはずのiOS Appではメモ欄の枠が消えている。

|iOS App|MacOS Safari|
|---|---|
|![A87CA027-5FF7-43EF-8E9B-576E1F439381_1_102_o](https://user-images.githubusercontent.com/48097323/113480850-6ba54100-94d1-11eb-9581-c66c0da66ede.jpeg)|<img width="700" alt="スクリーンショット 2021-04-03 23 04 30" src="https://user-images.githubusercontent.com/48097323/113480790-28e36900-94d1-11eb-96f9-d6a6c70ae49e.png">|

**Comment by KanadeNishizawa** [comment]
機能面での致命的なバグではないけど、見た目で文字打てそうな感じがないし、iOS Appユーザーの割合高いのでだいぶ辛い

**Comment by takonasu** [comment]
iOSAppだけでなく、iOSのブラウザはすべて枠が消えていることを確認しました

**Comment by KanadeNishizawa** [comment]
あざます、じゃあiOS Safariで検証します!
