### ISSUE TITLE
土曜日の授業を入れると死ぬ

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#340]
undefined is not an object  `e[Ht(t.day)][t.period-1]`

**Comment by hayato24s** [comment]
検索画面や詳細画面の開講時限の表示で使いたいです。
Satは残しつつ、CourseListToTableだけ変更するのはどうでしょうか？
この辺でSatを除外するかんじで。
https://github.com/twin-te/twinte-front/blob/7c6d85225e8836ad07a4501872aa0b6190d3ee8b/src/usecases/courseListToTable.ts#L25

<img width="544" alt="スクリーンショット 2021-04-04 0 31 31" src="https://user-images.githubusercontent.com/68944024/113483321-c93f8a80-94dd-11eb-8a6e-aafd906e32db.png">
<img width="561" alt="スクリーンショット 2021-04-04 0 33 32" src="https://user-images.githubusercontent.com/68944024/113483325-ccd31180-94dd-11eb-9d22-01590b376385.png">

**Comment by HikaruEgashira** [comment]
なるほど、、
オッケーです
