### ISSUE TITLE
タッチ操作でドロップダウンを選択すると引っ込まない

### ISSUE THREAD

**Issue by SIY1121** [twin-te/twinte-front#358]
一瞬引っ込むようなアニメーションが表示されるが戻ってくる
![anim](https://user-images.githubusercontent.com/17082836/113500404-a56d5a80-9558-11eb-8d56-941700a6cb2a.gif)

**Comment by hayato24s** [comment]
vue-click-awayとdropdown-contentの処理が両方とも呼ばれちゃっているからかな？
