### ISSUE TITLE
お知らせページ

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#361]

**Comment by HosokawaR** [comment]
Twin:te と twins を混同して Twin:te で履修登録をしてしまう人がいないように早急に実装したいです。
そのためバグではありませんが、優先度２に引き上げさせてもらいました。

**Comment by KanadeNishizawa** [comment]
一応、V2のお知らせ機能の移植という前提でのデザインデータは存在しています。(V3開発当初から移植することは決まっておりデザインデータも存在していたが、当時優先度が低かったのでV3のリリースには間に合わなかった)
データ構造は変わらない(by @hikaruegashira)らしいので、スピードを重視するならV2のものを元にこれで作るのが一番実装コストが低いかな？と思います。

(ただ、Slackでの議論を見るに告知の形をまったく変える可能性もありそうなので、あくまで「アプリ内で完結するお知らせを作るなら」のデザインです。)

https://www.figma.com/file/ofC6dBEU96Tp3IlrobCtlJ/App-V3?node-id=0%3A1
<img width="547" alt="スクリーンショット 2021-04-07 23 32 05" src="https://user-images.githubusercontent.com/48097323/113885677-fbf9c380-97fa-11eb-9f6e-b46c6c09ed03.png">
<img width="741" alt="スクリーンショット 2021-04-07 23 32 31" src="https://user-images.githubusercontent.com/48097323/113885691-fe5c1d80-97fa-11eb-842d-67f0b527f225.png">
<img width="341" alt="スクリーンショット 2021-04-07 23 32 56" src="https://user-images.githubusercontent.com/48097323/113885706-0025e100-97fb-11eb-869a-18f29bbcaa19.png">

**Comment by HosokawaR** [comment]
とても助かります！ありがとうございます。とりあえずまずはこの形で実装しようと思います。後からかえることはできるので。
