### ISSUE TITLE
CourseCard の情報を豊富にする

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#366]
現状のこの情報量だけでは履修するときに力不足でした
![image](https://user-images.githubusercontent.com/45098934/113505922-a617e800-957c-11eb-8706-faa4b74c02fd.png)

- 推奨学年がわからない
- シラバスがない授業がある 末尾の/0/の違いか？

追加する分にはよいが、あたらしい講義を探すのには物足りなかった

**Comment by hayato24s** [comment]
推奨学年ほしいですね〜

**Comment by HosokawaR** [comment]
この Issue は https://github.com/twin-te/twinte-front/issues/496 に発展し https://github.com/twin-te/twinte-front/pull/516 でかいけつされた。
