### ISSUE TITLE
ドロップダウンのキャンセルがしにくい

### ISSUE THREAD

**Issue by takonomura** [twin-te/twinte-front#379]
今だと下矢印でしかキャンセルができないが、画面の他部分をクリックや esc キーでキャンセルしたい。

<img width="94" alt="Screen Shot 2021-04-05 at 15 04 43" src="https://user-images.githubusercontent.com/22152877/113542917-4246fb00-9620-11eb-9079-9bbeb995221b.png">

**Comment by HosokawaR** [comment]
本来なら閉じるはずだが、#358 と同様のバグによって閉じられていない模様.
