### ISSUE TITLE
CSV追加がうまくいってない

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#38]
## 概要

- 科目追加ダイアログ内のCSV追加が上手くいってない
- readerの使い勝手がわるいので直し方がわからない
- とりあえずwarning出して対処してる

## 目的

- バグです

## 提案内容

🤷‍♂️

## タスク

- [ ] onFileChange関数の修正
- [ ] csvLectureListにCSVをパースした授業番号配列が入るようにする
- [ ] 169行目のwarningのダイアログを消す

## 変更するファイル

- /src/component/def-dialog-add.vue

## 優先度

4

**Comment by HikaruEgashira** [comment]
リファクタリングもやってない最悪のファイル

**Comment by SIY1121** [comment]
原因かはわからないけど、動かしてみたらcsv読み込み後のsearchで `https://dev.api.twinte.net/v1/lectures/search?q=GB11954%0D&year=2019` みたいなリクエスト飛ばしてて、講義IDの末尾に `%0D` が入ってるので検索結果が空になってる。
`%0D`は `\r` 相当だから おそらく twinsから吐かれるcsvの改行コードが `\r\n` の可能性がある。

https://github.com/twin-te/twinte-front/blob/9578bc7e878cfcccb4a2df09e393c8df467ec5ee/src/components/def-dialog-add.vue#L183-L188

で `\r\n` でsplit してみたら動くかも？

**Comment by HikaruEgashira** [comment]
やったぜ
