### ISSUE TITLE
モジュールの切り替えを横スクロールでやりたい

### ISSUE THREAD

**Issue by hayato24s** [twin-te/twinte-front#382]
2タップは許容できません。履修仮組みのこの時期はモジュールを切り替える頻度が多く、タブレットやスマホではかなりストレスになります。また、Twin:teを利用しているユーザーの多くはスマホ版を利用していると思われる、かつ、kdbが使いづらいからTwin:teで履修仮組みを行う人が多いと考えられるため、実装する価値は十分あると思います。

**Comment by HikaruEgashira** [comment]
横スクロールが意外と解決策にはなっていなくって、タップ数は最短1スクロール、最高5スクロールで不安定なUXになっちゃう。横スクロールは前回でも結構クソUIトップ候補だったので、革新的な解決策が出るまではこれはなし派

**Comment by HosokawaR** [comment]
両方とも実装するのはどうでしょうか。カレンダーアプリなどでも、横スクロールで切り替えつつ、上のカレンダーボタンで月を切り替えれるなどといった動作はよくあります。目的１つに対し操作が２つあってはだめということはないと思います。
横スクロール、現行の選択式、どちらも一長一短なので両方つけるのが良いのかと思いました。

**Comment by HikaruEgashira** [comment]
#394 が結構良くって、HosokawaR君の意見も合わせて、モジュールが縦にスクロールできる（OR 上下矢印が実装される）のが結構良さそうに感じた。
UIに関わるところは、ゆっくり詰めるべきなので、 #394 を先に実装してみたい。
