### ISSUE TITLE
ドロップダウンのオプションについて

### ISSUE THREAD

**Issue by hayato24s** [twin-te/twinte-front#395]
大前提として、講義は`モジュール+特殊曜日`もしくは、`モジュール+曜日(月〜日)+時限(1〜8)`を持つべきである。つまり、`module`と`day`が`Unknown`になるというのは例外として扱うべきであり、ホーム画面のその他の欄に表示するのが良いと思われる。#380
問題となるのが、編集ページでの`その他`の扱いである。`その他`が選択された時に`集中,応談,随時`のどれに該当するのかがわからず、#385 のようなバグが起こっている。（update時に`その他`が`月`に変換されている）僕はやはり、`集中、応談、随時`のオプションを時限のドロップダウンに持つのが良いと思う。ドロップダウンが長くなりすぎてしまう問題も土日授業に対応するかどうかの表示設定を追加すれば良いのではないだろうか？普段土曜授業を取らない僕としては”土日”の欄は邪魔だなと感じてしまう。

### 編集ページ
|     | 学期 | 曜日 | 時限 |
|:---:|:---:|:---:|:---:|
|指定なし|Unknown |Unknown |0 |
|その他|- |集中+応談+随時 |-|

### 検索ページ
|     | 学期 | 曜日 | 時限 |
|:---:|:---:|:---:|:---:|
|指定なし|春秋ABC+夏休+春休|月~日+集中+応談+随時 |0~8 |
|その他|- |集中+応談+随時 |-|

<img width="333" alt="スクリーンショット 2021-04-06 16 41 17" src="https://user-images.githubusercontent.com/68944024/113676100-0468d600-96f7-11eb-8198-9d5ad325f19d.png">
<img width="326" alt="スクリーンショット 2021-04-06 16 41 34" src="https://user-images.githubusercontent.com/68944024/113676171-19456980-96f7-11eb-8da3-1e7716a05f20.png">
<img width="366" alt="スクリーンショット 2021-04-06 15 06 47" src="https://user-images.githubusercontent.com/68944024/113675515-67a63880-96f6-11eb-9872-6306bb512f83.png">

**Comment by HosokawaR** [comment]
> 大前提として、講義はモジュール+特殊曜日もしくは、モジュール+曜日(月〜日)+時限(1〜8)を持つべきである。

モジュール+特殊曜日+時限(1~8)のパターンもあります。

**Comment by hayato24s** [comment]
特殊曜日の時は時限の情報を表示していない。編集時の初期値としてのみユーザーには表示される
