### ISSUE TITLE
科目番号の先頭に一致するものだけ表示されてほしい

### ISSUE THREAD

**Issue by hayato24s** [twin-te/twinte-front#398]
科目番号で検索する際（数字と英語の大文字）、科目番号の先頭に一致するものだけ表示して欲しい。
画像の一枚目ではなく、二枚目のような講義だけ表示されてほしい。
@SIY1121 

<img width="968" alt="スクリーンショット 2021-04-07 13 33 03" src="https://user-images.githubusercontent.com/68944024/113810799-f58d2c80-97a5-11eb-9161-ae16b463881f.png">
<img width="939" alt="スクリーンショット 2021-04-07 13 33 25" src="https://user-images.githubusercontent.com/68944024/113810802-f756f000-97a5-11eb-8c82-97adf4e1cfeb.png">

**Comment by HosokawaR** [comment]
https://github.com/twin-te/twinte-front/pull/516 の時点では実現されたので閉じる
（科目番号の先頭一致はもっと前から実現できていたかも）

バックエンドは https://github.com/twin-te/course-service/commit/084f46228e473aad1bcb3947ca98593a012ad589 で実装された
