### ISSUE TITLE
Androidでキーボードを出すと、モーダルの表示が崩れる

### ISSUE THREAD

**Issue by SIY1121** [twin-te/twinte-front#40]
## 概要
Androidでキーボードを出すと、モーダルの表示が崩れる

## 再現手順
textareaにフォーカスする
![Screenshot_20191209-105714](https://user-images.githubusercontent.com/17082836/70401453-fa878200-1a72-11ea-979c-6b8367f0e8fd.jpg)
![Screenshot_20191209-105719](https://user-images.githubusercontent.com/17082836/70401456-fce9dc00-1a72-11ea-991e-0d07e9dcf648.jpg)

## 修正しないとどう困るか
textareaが小さくなってせいぜい2行しか表示出来ないので見にくい

## 原因
キーボードがでるとvhも変わってしまう

## 修正案
フォーカス前のvhをとっておいて、高さを絶対値指定する…？

**Comment by HosokawaR** [comment]
これはもう閉じてもいいと思います。
