### ISSUE TITLE
タグ機能

### ISSUE THREAD

**Issue by takonomura** [twin-te/twinte-front#403]
バックエンドには実装されてそうだけど結局フロントエンドには無さそう

最低限必要そうな作業は以下の3点だと思われる

* タグの作成や編集のできるページの追加
* 科目の編集画面からタグの追加
* 科目詳細ページにタグの表示

それ以外に以下の機能が実装されるととても嬉しい

* そのタグのついた科目の合計単位数
* タグのついた科目を時間割画面で別の色に (必修だったり対面授業だったりを別の色にして見やすくしたいので)

**Comment by HosokawaR** [comment]
この Issue は https://github.com/twin-te/twinte-front/issues/497 に発展し https://github.com/twin-te/twinte-front/pull/504 で解決された。
※タグによるコマの色付けは未実装
