### ISSUE TITLE
scheduleが[]な講義を編集しようとすると開講時限のドロップダウンが表示されない

### ISSUE THREAD

**Issue by hayato24s** [twin-te/twinte-front#406]
<img width="357" alt="スクリーンショット 2021-04-07 20 37 50" src="https://user-images.githubusercontent.com/68944024/113866743-a3b9c600-97e8-11eb-8253-4d9e630b14ff.png">

**Comment by hayato24s** [comment]
これは仕様ですか？

**Comment by HikaruEgashira** [comment]
考慮してなかったけど、確かにない場合の初期状態は「一つドロップダウン表示」だと思うので修正したいね。
