### ISSUE TITLE
時間割が見切れる

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#407]
iPhone SE （320 * 568）など一部のミニスマホでは時間割が見切れます。
これは一部の講義がとても長い名前だった場合、各グリッドがその長さに合わせようとするからです。
![image](https://user-images.githubusercontent.com/45098934/113877550-c7ced480-97f3-11eb-8be9-6b62177e5b22.png)

**Comment by HosokawaR** [comment]
でもスクロールはできるので、時間割が見れない！ってことはないです。

**Comment by hayato24s** [comment]
僕の端末だとスクロールすらできなくて5.6限が見れません。

**Comment by HosokawaR** [comment]
> でもスクロールはできるので、時間割が見れない！ってことはないです。
この発言は chrome のデベロッパーツールでの確認情報なので webView だと問題があるのかもしれません

**Comment by HosokawaR** [comment]
正直これ対処法がわからなく空白の行、高さが低い行を狭めればある程度の人は救えそうです。しかし根本的解決策になっていません。

**Comment by KanadeNishizawa** [comment]
おそらくですが、https://github.com/twin-te/twinte-front/pull/381 が関係してそう(このグリッドレイアウトへの置換を含めた変更をdeployするまでは正常だったので)なので、このPR自体を一旦revertした方が良いかもしれません。
早めに取り込みたいPRでしたが、明日から新学期の今夜で、かつすぐに治せそうにない致命的なバグ(この見切れ以外にもレイアウト崩れがある)が生じているのであれば、修正が完了してからmergeしなおした方が賢明かな…？と思います。

**Comment by KanadeNishizawa** [comment]
シュッと直る見込みがあるなら別ですが、結構複雑な要因の気がするので
(あとTwitterで調べた感じ結構困っている人がいたので早急に対応しないとマズそう)

**Comment by hayato24s** [comment]
そうしましょう

**Comment by HosokawaR** [comment]
ぱっと調べた感じ、どうやら iOS の webView は grid に弱いみたいです…

**Comment by HosokawaR** [comment]
これ今度から dev に先にデプロイして、実機テストが必要ですね

**Comment by hayato24s** [comment]
これ、.mainにheightを指定していなからですかね？

**Comment by KanadeNishizawa** [comment]
ワンチャン https://github.com/twin-te/twinte-front/pull/397 と依存関係にありそうなので、念のためこちらもrevertさせてもらいます

**Comment by hayato24s** [comment]
.main__contentsに指定している
@include height-without-headerを.mainに指定すれば動くかも

**Comment by HosokawaR** [comment]
たしか宍戸くんが
> これ、.mainにheightを指定していなからですかね？

が原因だと後に発見したので閉じます。
