### ISSUE TITLE
手動授業追加ができない

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#414]
現在原因を解明中
![image](https://user-images.githubusercontent.com/45098934/114164750-a04c4900-9966-11eb-9359-155551161ddc.png)

**Comment by hayato24s** [comment]
apiを叩くタイミングでエラーが発生しているのだと思われます。
ちなみに、手動で作成する授業には`code`は存在しません。
#458 の時点で僕が確認した限り、手動で授業を追加することが可能でしたので閉じますね。
