### ISSUE TITLE
通知設定のopenSettings()に適用中のテーマを渡す

### ISSUE THREAD

**Issue by itsu-dev** [twin-te/twinte-front#437]
# 起きている問題
モバイルアプリにおける「通知設定」で出てくる設定画面は各アプリのネイティブ実装になっているが、その画面には適用中のテーマが適用されない。
# 改善案
openSettings()関数の引数に新しく適用中のテーマ(dark/light)を渡し、アプリ側でテーマの判別を可能にする。

**Comment by HikaruEgashira** [comment]
issueありがとうございます！
改善策の方法がshare関数でやってることと同じなので早めに実装出来ると思います:+1:

https://github.com/twin-te/twinte-front/blob/main/src/templates/Sidebar.vue#L138
