### ISSUE TITLE
Googleでのログイン

### ISSUE THREAD

**Issue by Mimori256** [twin-te/twinte-front#444]
![Screenshot 2021-05-03 174832](https://user-images.githubusercontent.com/80367947/116857518-e7f98400-ac37-11eb-84f3-3ab8743da50b.png)

FirefoxでログインしようとするとGoogleでログインが表示されなくて、Chrome系でログインする場合はGoogleでログインが表示されます。これは仕様ですか？

**Comment by HikaruEgashira** [comment]
ご報告ありがとうございます。自分の環境でも出ませんでしたが、仕様ではないです。
自分も原因がわからいないので、help wanted

**Comment by HosokawaR** [comment]
現在（2022-12-18）の Windows Firefox 108.0.1 では再現しなかった。
バグの報告から時間が立っているので閉じる。

正常な様子
![image](https://user-images.githubusercontent.com/45098934/208283294-b7ca9194-eaa7-4cb7-b48f-dbf4df96bb6a.png)
