### ISSUE TITLE
 twinte-openapi-spec の submodule を master に追従させたい

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#460]
バックエンドの実装タイミングよりも[twinte-openapi-spec](https://github.com/twin-te/twinte-openapi-spec)の更新が早くなってしまう場合を考慮する必要がある

**Comment by HikaruEgashira** [comment]
メリット知りたい！
これまでは最新のspecを利用した実装をするときにtwinte-openapi-specを更新する運用だったけど不便に感じなかった

**Comment by HosokawaR** [comment]
自分でもなぜ当時こう考えたのかを忘れたので Close
