### ISSUE TITLE
空の授業を検索したときの条件消す

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#464]

**Comment by HosokawaR** [comment]
この Issue は時間割の空き時間をタップしたときに、その時間のみを検索対象に含めるフィルタに気づかず、検索結果が表示されないことによる混乱を解消する目的があった。
しかし https://github.com/twin-te/twinte-front/pull/516 により小さく現在のフィルタが表示されるようになったのでその問題は解決された。
よって close する。
