### ISSUE TITLE
KdB の最終更新日を記載

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#465]
~バックエンドにlast updateをはやす必要があり~
「毎朝6時に更新されます」って入れる

**Comment by SIY1121** [comment]
@HikaruEgashira 
これどういう要件だっけ？
授業ごとのlastUpdate？

**Comment by HikaruEgashira** [comment]
searchのレスポンスにKdBのlastUpdateがあるイメージかな（詳細Slack）

**Comment by HikaruEgashira** [comment]
変更→追加「毎朝6時に更新されます」

**Comment by HosokawaR** [comment]
@KanadeNishizawa 本件のデザインはありますか？

**Comment by KanadeNishizawa** [comment]
@HosokawaR  ありません！ちょいとお待ちください…(できたらfigmaの方でメンションします )

**Comment by HosokawaR** [comment]
ありがとうございます！
