### ISSUE TITLE
Storybook 導入

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#470]
導入したい理由は以下です。

1. コンポーネントを開発時にプレビューする場所がほしい
2. コンポーネントの挙動をまとめた場所がほしい
  Twin:te V3 の開発から時間が経過しコンポーネントの振る舞いを忘れているのも大きいです…

ちなみに Twin:te V3 の開発時は Storybook が Vue3 に対応していなかったので導入を見送っていましたが
もともと導入する意思はあったような気がします。

**Comment by HikaruEgashira** [comment]
https://github.com/storybookjs/storybook/issues/12505

これがめっちゃハマるやつ

**Comment by HosokawaR** [comment]
ありがとうございます。
うーん これは悩みですね
