### ISSUE TITLE
アーキテクチャについてチーム内で合意を取りドキュメント化する

### ISSUE THREAD

**Issue by hayato24s** [twin-te/twinte-front#480]
> 想定のアーキテクチャとしては、
>
>- usecaseはフレームワーク非依存
>- リアクティブなやつはhooksに置く（この場合は`useTag`など）
>
>あたりが想定だった。
>機能追加終わったらアーキテクチャのドキュメント化も含めてチーム内で話し合おう！

_Originally posted by @HikaruEgashira in https://github.com/twin-te/twinte-front/pull/478#discussion_r835738679_

**Comment by HosokawaR** [comment]
> 機能追加終わったらアーキテクチャのドキュメント化も含めてチーム内で話し合おう！

始めるのはタグ、検索表示改善、カレンダー連携の実装が終わったあたりでいかがでしょうか。
逆に終わりは新メンバーが開発に入るまでが一つの目標かと思います。。

**Comment by hayato24s** [comment]
## Problems
- `usecase` が `api` や `vuex` に依存している
- `entity` が `api` や `view` に依存している
    - `RegistereCourse` や `CourseCard` など
- `view` の いわゆる `single source of truth` が曖昧
- テストがしにくい

## Solutions
### 1. Architecture
[実装クリーンアーキテクチャ](https://qiita.com/nrslib/items/a5f902c4defc83bd46b8) を踏まえて、以下のアーキテクチャを提案します。

![Architecture](https://user-images.githubusercontent.com/68944024/160445065-49dc50ff-ae86-4f46-b713-fa8ddc45e78a.png)

例えば、授業詳細画面でメモの更新を行うときは以下のような処理が行われます。
1. `Store.State` をもとに `View` が描画されている
2. メモの更新を行うため `View` から `Store.Action` を呼び出す（`updateMemo`みたいな）
3. `Store.Action` から `UseCase` を呼び出す（`updateRegisteredCrouse`みたいな）
4. 更新された `ViewModel` を取得するため `Store.Action` から `Presenter` を呼び出す（`createViewModelCourseみたいな）
5. `Store.State` を 4で取得した `ViewModel` に更新する
6. `Store.State` が変更されたため `View` が更新される


### 2. フロントエンド独自の `Entity` を定義する
以下のようなものを想定しています。
```
import { Dayjs } from "dayjs";

export type Module =
  | "SpringA"
  | "SpringB"
  | "SpringC"
  | "SummerVacation"
  | "FallA"
  | "FallB"
  | "FallC"
  | "SpringVacation";

export type WeekDay = "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat";

export type WeekEndDay = "Sun";

export type NormalDay = WeekDay | WeekEndDay;

export type SpecialDay = "Intensive" | "Appointment" | "AnyTime";

export type Day = NormalDay | SpecialDay;

export type Period = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8";

export type NormalSchedule = {
  module: Module;
  day: NormalDay;
  period: Period;
  room: string;
};

export type SpecialSchedule = {
  module: Module;
  day: SpecialDay;
  period?: Period; // 特殊授業は時限が指定されていない授業もある
  room: string;
};

export type Schedule = NormalSchedule | SpecialSchedule;

export type Method = "FaceToFace" | "Synchronous" | "Asynchronous" | "Others";

export type Tag = {
  id: string;
  name: string;
  order: number;
};

export type Course = {
  id: string;
  year: number;
  code: string;
  name: string;
  instructor: string;
  credit: string;
  overview: string;
  remarks: string;
  recommendedGrades: number[];
  methods: Method[];
  schedules: Schedule[];
};

export type RegisteredCourse = {
  id: string;
  year: string;
  code?: string; // 手動で追加した授業の場合は `null`
  name: string;
  instructor: string;
  credit: string;
  methods: Method[];
  schedules: Schedule[];
  memo: string;
  attendance: number;
  absence: number;
  late: number;
  tags: Tag[];
};

export type User = {
  id: string;
  name: string;
};

export type SchoolCalendarModule = {
  year: number;
  module: Module;
  start: Dayjs;
  end: Dayjs;
};

export type SchoolCalendarEvent = {
  date: Dayjs;
  name: string;
};

export type News = {
  id: string;
  title: string;
  content: string;
  publishedAt: string;
  read: boolean;
};

export type Error = {
  message: string;
};
```

### 3. ViewModel を作成する
- UI用の型

### 4. `vuex` を廃止して `Store` を自前で実装する
- 現状、`store.getters` に型がつかない（致命的）
- [Vue.js/状態管理](https://v3.ja.vuejs.org/guide/state-management.html#%E3%82%BB%E3%82%99%E3%83%AD%E3%81%8B%E3%82%89%E4%BD%9C%E3%82%8B%E3%82%B7%E3%83%B3%E3%83%95%E3%82%9A%E3%83%AB%E3%81%AA%E7%8A%B6%E6%85%8B%E7%AE%A1%E7%90%86) のような感じで自前で実装した方が良いと思う。
- `Store` は `State` と `Action` を持つ
- `Store.State` の型は `ViewModel` で定義する
- この `Store.State`（`ViewModel`） は `View` の`single source of truth` である。 
- データの流れを一方向にする（[Vuex とは何か？](https://vuex.vuejs.org/ja/)より）
<img width="640" alt="flow" src="https://user-images.githubusercontent.com/68944024/160447361-05abdae6-48f9-4faa-b591-4d615268fa00.png">


### 5 `Presenter` を作成する
- `Entity` から `ViewModel` を作成する

### 6. `Repository` を作成する 
- テストをしやすくするため
- [実装クリーンアーキテクチャ](https://qiita.com/nrslib/items/a5f902c4defc83bd46b8) より

## References
- [実装クリーンアーキテクチャ](https://qiita.com/nrslib/items/a5f902c4defc83bd46b8)
- [Vue.js/状態管理](https://v3.ja.vuejs.org/guide/state-management.html#%E3%82%BB%E3%82%99%E3%83%AD%E3%81%8B%E3%82%89%E4%BD%9C%E3%82%8B%E3%82%B7%E3%83%B3%E3%83%95%E3%82%9A%E3%83%AB%E3%81%AA%E7%8A%B6%E6%85%8B%E7%AE%A1%E7%90%86)
- [Vuex とは何か？](https://vuex.vuejs.org/ja/)
