### ISSUE TITLE
Androidアプリ実行時のみ、「設定」メニューを追加してほしい

### ISSUE THREAD

**Issue by SIY1121** [twin-te/twinte-front#51]
## 概要
Androidアプリ実行時のみ、「設定」メニューを追加してほしい
## 目的
- Androidアプリ開発に使用したOSSのライセンス表示画面の確保
- バージョン情報や、ウィジット設定などのAndroid限定機能の呼び出し
## 提案内容
Androidアプリ実行時のみ、サイドメニューに「設定」メニューを追加してほしい。
（フロントでも設定画面を追加する予定があるなら「Androidアプリの設定」とかにしといたほうが良い？）

## タスク
AndroidWebViewからグローバルなオブジェクト `android` を注入するので

- [ ] `typeof android !== "undefined"` で設定メニューを出すかを判定
- [ ] 設定をタップしたら `android.openSettings()` を実行する

**Comment by HikaruEgashira** [comment]
Cannot find name 'android'の回避はどうすればいいですか？

**Comment by SIY1121** [comment]
いくつか方法はあるけど使うファイルの一番上で
```typescript
declare global {  
    interface Window {  
        android?: {
          openSettings: () => void
        }
    }  
}
```
ってやっとくと
```typescript
if(window.android) {
  window.android.openSettings()
}
```
ってかけるはず
