### ISSUE TITLE
重複モーダルが重複していないのに出現する

### ISSUE THREAD

**Issue by hayato24s** [twin-te/twinte-front#514]
授業を追加すると重複モーダルが重複していないのに出現されます。
`store.state.courses` で年度に対応した時にバグったのだと思われます。

**Comment by hayato24s** [comment]
@HosokawaR 検索改善のついでに対応できたりしますか？
該当ファイルは`usecases/getDuplicatedCourses.ts`です。

**Comment by HosokawaR** [comment]
OK です。
ただ検索改善の PR と趣旨とはずれるので新規 PR で処理します。
