### ISSUE TITLE
ダークモード対応

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#53]
## 概要

カラーテーマを変更できるようにしたい。
figmaで完全なダークテーマが作成されていない
設定項目を追加する必要が出てくるかも

## 目的

現代的アプリケーションっぽく
いろんな色があったらうれしい

## 提案内容

参考 - マテリアルデザインのダークテーマガイドライン
https://material.io/design/color/dark-theme.html

## タスク

- [x] 変数用sassをassets/cssに作成
- [x] 現在カラーが直打ちのため、sassの変数にする
- [x] figmaでダークテーマカラーコードを作成
- [x] 設定で変更できるように

## 優先度 3

**Comment by KanadeNishizawa** [comment]
ダークテーマのデザインデータ案たち
検討事項がいくつかあるので（リンク先参照)まだ完全に決定ではないけど、デザインは大体こんな感じの方向性
https://www.figma.com/file/4WzrwrZKO8uiSyTQYgjrs8/App?node-id=218%3A3578
