### ISSUE TITLE
CI で yarn global cache をキャッシュする

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#548]
相談っぽい Issue です。

[このような](https://github.com/twin-te/twinte-front/blob/c692553f3347862903924a9a562178b875c76ade/.github/workflows/ci.yml#L17)ところとか`node_modules`を直接キャッシュしないで yarn の global cache をキャッシュしたほうが速いのですかね？
現行のやり方だと`yarn.lock` が少しでも変わるとすべて fetch し直しますが、上記のやり方なら差分だけ fetch してくれそうです。

`node_modules` を直接キャッシュする場合は [actions/setup-node のこれ](https://github.com/actions/setup-node/blob/eeb10cff27034e7acf239c5d29f62154018672fd/README.md#caching-global-packages-data)とかが使えそうです。

**Comment by HikaruEgashira** [comment]
setup-nodeのやつ使う方針がいいと思います :+1:
