### ISSUE TITLE
Error Refactoring

### ISSUE THREAD

**Issue by hayato24s** [twin-te/twinte-front#555]
## 概要
現状のエラーについて把握して、適宜エラーを追加し、エラー処理を充実させる。

## 追加したいエラー
- NotFound : idを指定して授業を取得しようとしたが、見つからなかったときなどに使用したい。
- ValueError : 型は正しいが値が適切ではないときに使用したい。[参考 : pythonのValueError](https://docs.python.org/ja/3/library/exceptions.html#ValueError)
- UnauthorizedError : 未認証なのに、ログイン済みのユーザーしかアクセスできないデータにアクセスしようとした時に使用したい。

**Comment by HosokawaR** [comment]
現状のエラー処理について簡単に実装や設計意図を解説します。

# 実装・意図

現在のエラー処理はほぼ https://github.com/twin-te/twinte-front/blob/main/src/usecases/error.ts で実装されたものです。この PR に当時の意図が書かれています。

以下エラー周りの処理について

 - エラー定義
 - throw エラー
 - catch エラー 

の3つの観点から説明します。

## エラー定義

エラー定義は[このファイル](https://github.com/twin-te/twinte-front/blob/main/src/usecases/error.ts)でしています。
Error Class を継承する形で様々なエラーを定義しています。
またエラーによっては必要なインスタンスプロパティを追加しています。たとえば `NetworkAccessError` では Status Code を知りたいため `status` が追加されています。

## throw エラー

エラーを投げたいときは上記のエラー定義で詳解したクラスをインスタンス化して throw します。
例えば[ここ](https://github.com/twin-te/twinte-front/blob/7e4dd1ca0ee9c9a2decdaf514d867601db9932fe/src/usecases/getCourseByCode.ts#L34)のように。
（※余談ですが、`NetworkAccessError` が`originalResponse`を引数に受け取るのは密結合なのでこれは直したいなと思っています。）

ライブラリから投げられる Error をそのまま throw しないで、ライブラリから投げられる Error を catch した上で、独自の Error Class を throw する理由は、階層によって知りたいエラーのレベルが違うからです。またこのときにインスタンスプロパティに適切な値を設定することもあります。[Ex](https://github.com/twin-te/twinte-front/blob/7e4dd1ca0ee9c9a2decdaf514d867601db9932fe/src/usecases/readCSV.ts#L49)

## catch エラー

エラーは throw で投げられるので catch で受け取ります。
また catch 時には設定されたプロパティを取り出してエラーメッセージに反映することもあります。([Ex](https://github.com/twin-te/twinte-front/blob/7e4dd1ca0ee9c9a2decdaf514d867601db9932fe/src/pages/add/search.vue#L471))

## 今後の展望

 - Result 型とか導入したい
   - エラーを正しく handling したかどうかを型検査で保証したいため

**Comment by hayato24s** [comment]
## 例外
- NotFoundError
  - 指定されたリソースが見つからない
- ValueError
  - 型は正しいが値が適切ではない
- UnauthorizedError
  - 未認証の状態で権限が必要なリソースにアクセスした
- NetworkError
  - ネットワークにアクセスできない
- InternalServerError
  - 上記以外のエラーがサーバー内で発生した

## 参考
- [例外処理 — 仕事ですぐに使えるTypeScript  ドキュメント](https://future-architect.github.io/typescript-guide/exception.html)
- [TypeScript のエラーハンドリングを考える](https://qiita.com/frozenbonito/items/e708dfb3ab7c1fd3824d)
- [unknown型 | TypeScript入門『サバイバルTypeScript』](https://typescriptbook.jp/reference/statements/unknown#:~:text=TypeScript%E3%81%AEunknown%E5%9E%8B%E3%81%AF,%E5%80%A4%E3%82%82%E4%BB%A3%E5%85%A5%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82)
