### ISSUE TITLE
未認証でできること

### ISSUE THREAD

**Issue by hayato24s** [twin-te/twinte-front#558]
未認証の時に何ができて何ができないのかわからないので、どなたかわかる方がいましたら教えてもらえないでしょうか？お願いします🙇‍♂

ちなみに、現在はログインしないと以下のようなモーダルが出現するのですが、「あとで」を選択するとログインせずにアプリを使用することができます。授業の検索や登録はできません。

強制的にログインさせるという手段もあるのかなと思っています。

<img width="300px" src="https://user-images.githubusercontent.com/68944024/183247864-cdf6bb81-52f7-4c76-937f-652518385834.png">
️

**Comment by HikaruEgashira** [comment]
これは確かに。
> /information 以外は全部認証必須にしてたはず
なので未認証時はリダイレクトとかもケースによってはありそう。

@KanadeNishizawa 
ウェルカム要素入れとくならば、単に閉じられないようにするとかどう？

**Comment by HosokawaR** [comment]
検索などが未認証時にできない理由ってなんですかね…？
UX 的には未ログインであってもできる操作はユーザになるべく見せたほうがいいのかなと思いました。
認証要求のタイミングは授業の追加時やメモの追加時でいいかと。しっかりログイン要求の処理を書くのが大変そうではありますが、今後エラーまわりも整備されてくれば `UnauthorizedError` の処理漏れなども防止されると考えています。
またブラウザなどは URL の履歴によって未ログイン状態でいきなり検索画面に繊維してしまうという挙動も十分に考えられます。

**Comment by hayato24s** [comment]
ログインしないとできないことにチェックをお願いします。

- [ ] 授業の検索
- [ ] 授業の登録
- [ ] 授業の編集（メモとかタグの紐付けとか担当教員とか）
- [ ] 授業の削除
- [ ] タグの登録
- [ ] タグの編集
- [ ] タグの削除
- [ ] お知らせの取得
- [ ] フィードバックの送信
- [ ] イベントの取得（通常日課とか振替授業の時の水曜日課とか）
- [ ] モジュール情報の取得（現在のモジュールを取得するときに使用される）
- [ ] 設定の変更（ダークモードとか）
- [ ] 時間割のシェア？
- [ ] ユーザーのログイン情報の確認

**Comment by HikaruEgashira** [comment]
サーバー側をシンプルにするために、認証前提のサービスにしてる認識。特に大きなメリットなかったからね、、
もしも未認証でも使えるようにすると、ありがたみが増えそうな例があるといいかも。

特に時間割のシェアや口コミのシェアみたいなサービスが追加されると、、？

**Comment by HikaruEgashira** [comment]
ユーザーストーリ書いたら、Twin:teの基本機能が全て認証の後にあるから、
論理的には認証前提になってるのが理にかなっている。

「パソコンユーザーが筑波大学の授業検索したい」ってケースは認証を必要としないから、
そういった想定で機能を提供する場合は未認証でも使えるようにしたいね

**Comment by HosokawaR** [comment]
> ユーザーストーリではTwin:teの基本機能が全て認証の後にあるから、
論理的には認証前提になってるのが理にかなっている。

説明不足でした。確かにユーザストーリはすべてログインを前提としています。
一方で僕の考えではログインしなくてもこのアプリでどのようなことができるのかをチラ見させ、ユーザにログインする / しないのための選択のための情報を多く提供するのが良い UX だと考えていました。
Pinterest や Amazon などと似た挙動です。（これらは商業サービスなので一概に同じとは言えませんが…）

**Comment by HosokawaR** [comment]
ただ僕の話は理想論なので現実的にコストが高いならログイン前提がいいと思います。
たくさん書いてなんなのですが、特に強いこだわりがないので…

**Comment by HosokawaR** [comment]
これはもともとアーキテクチャ移行時の整理のために立てられた PR だった記憶がありますが、アーキテクチャ移行は完了したので閉じます
