### ISSUE TITLE
Code Owner の今後の方針について決める

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#565]
権限の委譲ってな

## 変更案
- 最低一人アプルーブでマージ可能にする（誰もレビューしてくれない場合がありうる）
- @HosokawaR と @hayato24s をオーナーに（レビューの譲り合いや二重レビューが起こるので効率が悪い。まあ確実ではあるが）
- フォルダ毎にオーナーを指定する（アーキテクチャ系hayato24s、アルゴリズム系hosokawaR的な）

で3番目の`フォルダ毎にオーナーを指定する`がレビュー効率的にいいと思うがどうでしょう？？
デザインは現状オーナーなしに変更かな。

@hayato24s @HosokawaR の意見で決定します。

**Comment by HosokawaR** [comment]
>最低一人アプルーブでマージ可能にする

個人的には Merge のスムーズさよりも、 全員が納得しない PR が Merge されてしまうことのほうが問題に感じているので、 2 Approve 必須でもいいんじゃないかなと思っています。
もし Approve が来ないなら Slack のメンションで催促してもいいかと。

ただ他の人が負担になると感じるなら、 最低 1 Aprrove を要件にするでもいいと思います。

> フォルダ毎にオーナーを指定する（アーキテクチャ系hayato24s、アルゴリズム系hosokawaR的な）

効率的だとは思うのですが、フォルダ毎にしっかり分けられるほど分業されていないのでやや難しいかなという感想です。

**Comment by HosokawaR** [comment]
@HikaruEgashira 
@HosokawaR と @hayato24s をオーナーに追加してもらいたいです。
あるいは Code Owner を廃止したいです。

デプロイ後に問題が発生した場合、HotFix を Merge することができないためです。

**Comment by HosokawaR** [comment]
「トラブルが起きたときに直ぐに Revert Commit をマージしたいけど Approve がないからできない」問題ですが、ロールバック的なものをブランチではないところで運用できれば解決しますかね…？

**Comment by HosokawaR** [comment]
2022-12-05 に MTG で色々話したことをまとめる

1. 結論 Code Owner は廃止。
    1. その代わりフロントエンドを普段触っている人から 2 Approve をもらい、必要に応じてデザイナーの Approve をもらってから Merge することを意識する。 
1. Code Owner を廃止した一番の理由は、緊急時に Revert などを一人で Merge できないため。
    1. 発展的には、緊急時に 0 Approve で Merge した場合に通知が飛ぶ仕組みや、緊急時に 0 Approve で Merge ができる Bot などを整備すると良い

**Comment by HosokawaR** [comment]
方針は決まったのでこの Issue は閉じる。
Code Owner の廃止は #610 のタスクとする。
