### ISSUE TITLE
【フィードバックページ】メアド記載を少々強くお願いする

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#578]
・すべての問い合わせの種類に「連絡先メールアドレス」を追記
・空欄の場合は赤文字で常に「運営が返信できないけどええか？」的な内容を書く

**Comment by HosokawaR** [comment]
「Twitter ID の入力を廃止」も要件に加えます

[経緯](https://discord.com/channels/1008574300787322980/1022811676602552390/1024856826069655582)

**Comment by HosokawaR** [comment]
当初の意見と変わって恐縮ですが、連絡先メールアドレスは必須でもいいと思いました。
理由は以下です。

1. 「必須入力じゃないけど極力入力してほしい」の UI が難しい
これを実現する UI として本 Issue では「赤文字で注意書きを書く」という案が出ていますが、Twin:te のデザインと合わない感じがあり、またそれを見たユーザには実質必須に見えるので、それなら必須項目でもいいかなと思いました。

2. 「必須入力じゃないけど極力入力してほしい」のスタンスを取ることにあまりメリットがない
当初は「メールアドレス（=個人情報）を入力することに抵抗がある人」にもなるべくフィードバックを送ってもらいたい、との意図で必須入力に反対でした。
ただ詳しくないユーザは Twin:te に SNS 認証した時点で大半の人は個人情報を渡している認識であり、これは懸念として正しくないと思いました。

**Comment by KanadeNishizawa** [comment]
入力項目として"運営からの返信を希望する/しない"の選択欄を追加するのもアリかなと思いました。
希望する人はメアド入力必須にする感じで…

「連絡先が無くて困る」のを最優先に防ぎたいので、"運営からの返信を希望する"チェックボックスを設置した上でその初期値をonにしておくのが良いかなと思います。

**Comment by takonasu** [comment]
”運営からの返信を希望する”チェックはかなり有効かもと思いました．
希望するならメアド入力を必須になるのはユーザも納得するかと

**Comment by HosokawaR** [comment]
「運営からの返信を許可する」はいいかがでしょうか。

この問題の発端は「ユーザ側では開発側からの連絡が必要かどうか判断できない」ということでした。

なのでユーザが返信を「希望」するよりも「許可」するほうが自然な気がしています。

**Comment by KanadeNishizawa** [comment]
@HosokawaR 

> この問題の経緯は「ユーザ側では開発側からの連絡が必要かどうか判断できない」ということでした。
> （Ex: フィードバックの送信者は普遍的なバグだと思って匿名で送信したが、実はその人固有のバグだっため、開発者はその人の連絡先が知りたかった）

それなら確かに「許可」というワードの方が良いと思います！
当初フィードバックページを作ってくれた時のように、デザインデータ無しでも既存のコンポーネントを組み合わせて良い感じに実装できそうだったらお願いしたいです。以下取り急ぎイメージをまとめたので参照してもらえると🙏
もし数日後とかでも構わなければデザインデータを作って渡すのでお知らせください！

####  イメージ
- 表示場所は「より詳しい原因解明のため…」という文章とテキストフィールドの間(画像参照)
- チェックボックスの右に「運営からの返信を許可する」というラベルをつける
- チェックボックスの初期値はon
- チェックボックスがonの時は連絡先テキストフィールドの入力が必須になり、offの時は任意になる

![スクリーンショット 2022-10-21 14 32 02](https://user-images.githubusercontent.com/48097323/197120269-480c43f8-c865-4862-8ed8-7e69f5cfa65a.jpg)

**Comment by HosokawaR** [comment]
ありがとうございます！

> 当初フィードバックページを作ってくれた時のように、デザインデータ無しでも既存のコンポーネントを組み合わせて良い感じに実装できそうだったらお願いしたいです。

複雑なデザインではないのでとりあえずつくって見ます。

> チェックボックスがonの時は連絡先テキストフィールドの入力が必須になり、offの時は任意になる

off のときは「連絡先の入力欄が非表示」のほうがいいかなと思ったのですがいかがでしょうか？
いただいたデザイン案だと「運営からの返信が許可」されていなくても、連絡先を送れることになりますが、返信できない連絡先を送られても困るかなという懸念がありました。

**Comment by KanadeNishizawa** [comment]
@HosokawaR 
> 返信できない連絡先を送られても困るかなという懸念がありました。

ぬお、本当にその通りですね…。思考停止してました、指摘あざます…！

できれば要素を完全に消したり表示したりするより、存在自体は示しつつdisabledにするのが文脈や見た目の上で理想的なんですが、TextFieldのコンポーネントは(わたしの想定不足で) disabledが無いんですよね。

なので、
- シュッと実装したければ、提示してくれた通りに表示/非表示での切り替え
- 多少手間でも良ければ、この機にTextFieldのdisabledを追加した上でそれを使う(disabledのstyleはButton等のコンポーネントと同様にopacityを下げるだけ)
という感じで、好きな方で実装してもらえると！よろしくお願いします。

**Comment by HosokawaR** [comment]
ありがとうございます！
余裕はあるので

> 多少手間でも良ければ、この機にTextFieldのdisabledを追加した上でそれを使う(disabledのstyleはButton等のコンポーネントと同様にopacityを下げるだけ)

の方針で行います！
