### ISSUE TITLE
ダークモードが OS のダークモードに追従していない

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#591]
## 背景

https://discord.com/channels/1008574300787322980/1009642761827385434/1032316065302192158 のデプロイ後に WEB,
 Android, iOS の端末それぞれでダークモードが解除される現象が発生した

端末のダークモード設定に追従する設定が聞いていない可能性がある

またこのデプロイではアーキテクチャの移行が含まれているので、永続化周り（LocalStorage）がリセットされた可能性がある

## 解決策

まず本当にダークモード設定に追従していないのかどうか考える
そうであるならば解決する

**Comment by HosokawaR** [comment]
> https://discord.com/channels/1008574300787322980/1009642761827385434/1032316065302192158 のデプロイ後に WEB,
Android, iOS の端末それぞれでダークモードが解除される現象が発生した

LocalStorage の扱い方がデプロイ前後で変更されたため、設定が初期化されたからである。

> まず本当にダークモード設定に追従していないのかどうか考える

そもそも端末のダークモードに追従するのが正しいのかという気がした。
現在の設定は「ダークモードの ON/OFF」なので、もし端末のダークモードに追従するなら「端末のダークモードに追従」というオプションが必要になる。
しかし現状はそのようなオプションはないため「ダークモードに追従していない」というのは正しい動作だと言えると思う。

**Comment by HosokawaR** [comment]
> 「ダークモードに追従していない」というのは正しい動作

なので Close する。
問題があれば Reopen してください。

**Comment by hayato24s** [comment]
ダークモードの設定などをバックエンドで保持するのも選択肢の一つですね。
