### ISSUE TITLE
検索した授業の詳細が表示できない

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#592]
![image](https://user-images.githubusercontent.com/37821819/196743746-39833357-0d0a-4ead-a0a0-56b0f39adb37.png)

詳細を見ようと赤色で囲んだボタンを押しても詳細が開かない

**Comment by HosokawaR** [comment]
これと関係ありそうですね
https://github.com/twin-te/twinte-front/issues/569

**Comment by takonasu** [comment]
CSVに関係ないってことか

今まで開けてなかったってｺﾄ...!?
