### ISSUE TITLE
Figma Education を使用

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#606]
現状に不自由がないならいいかもしれないが、機能制限に悩んでいるなら一考の価値あり
https://www.figma.com/ja/education/

**Comment by KanadeNishizawa** [comment]
実はすでにFigma Educationプラン利用しております！

ちなみにですが、このプランだと学生の資格を失ったメンバーはチームにアクセスできなくなってしまうため、もし今年度末時点に開発に困るレベルで”後任がいない&&属人化を解消できていない"という地獄が発生していた場合、逆にeducationプランから無料プランへグレードダウンせざるを得ない可能性すらあります…。
(流石にそれは回避したいので対処法考えときます)

![Uploading スクリーンショット 2022-12-13 21.01.49.jpg…]()

**Comment by HosokawaR** [comment]
ありがとございます。
すでに利用されていたのですね、良かったです！

> 開発に困るレベルで”後任がいない&&属人化を解消できていない"という地獄が発生していた場合、逆にeducationプランから無料プランへグレードダウンせざるを得ない可能性すらあります…。

これはたしかに大変ですね…

MEMO
すでに利用されていたのでこの Issue は Close する
