### ISSUE TITLE
Twin:te にインポートで `year` パラメータが要求されている

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#615]
## 問題

現在の Twin:te Front の実装では、インポートのクエリに `year` を要求しているように思える。（[該当コード](https://github.com/twin-te/twinte-front/blob/5e5877b533ffac1f3f6d2d1d976463adafe75cd7/src/ui/pages/import.vue#L119)）

しかし[開発者向けドキュメント](https://github.com/twin-te/twinte-landing-page/tree/main/docs)ではインポート時に年度は意図的に指定できないようになっているように思える。

これにより、[KdBもどき](https://make-it-tsukuba.github.io/alternative-tsukuba-kdb/)が発行する Twin:te にインポート URL が無効化されているように思える。
Sentry でもこれに起因すると思われるエラーをいくつか観測した。（Sentry Bot のコメントを参照）

KdB もどきが発行する URL の例）
`https://app.twinte.net/import?codes=1101102,1101202,1101302,1101402`

## 解決策
`year`はパラメータに要求するのではなく、その時の年度に合わせて暗黙的に設定する。
年度の決定ロジックは開発者向けドキュメントによると

> 表示設定またはメニューバーで表示されている年度に追加されます。

なので、それに合わせる

**Comment by HosokawaR** [comment]
@HikaruEgashira 当時この機能を実装してくださった記憶があるのですが、上記 Issue に間違いがあれば補足いただきたいです。

**Comment by HikaruEgashira** [comment]
自分の消し忘れって感じみたいです!!
簡単なやつなので、自分のほうでデバッグ->PRだします、、、

ref 実装時のPR: https://github.com/twin-te/twinte-front/pull/529

**Comment by HosokawaR** [comment]
https://github.com/twin-te/twinte-front/pull/616 で解決したので閉じる
