### ISSUE TITLE
授業場所を変更しても保存できない

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#618]
授業場所が空の状態から授業場所を入力しても保存ボタンがアクティブにならず保存できない
<img width="940" alt="image" src="https://user-images.githubusercontent.com/37821819/207763248-82ad0e32-3904-4a69-905d-669eda10ecd1.png">

**Comment by HosokawaR** [comment]
仕様ですかね…？

画像のように、授業場所に紐づく時間を選択していないからかと思われます。
データ構造では各時間に対して授業場所が紐づいているので、授業場所単体では存在し得ないためです。

![image](https://user-images.githubusercontent.com/45098934/207764714-566cb7e3-3f56-4513-a2ee-ee73960f5a47.png)

ただ仕様だとしても、わかりにくいみたいな Issue にはできるかもしれません。

**Comment by hayato24s** [comment]
仕様ですね。

**Comment by HosokawaR** [comment]
> ただ仕様だとしても、わかりにくいから治すべきみたいな Issue には変換できるかもしれません。

とりあえず「授業場所を変更しても保存できない」は仕様だったので閉じます。
