### ISSUE TITLE
検索イベントの収集コードが抜けている

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#639]
## 問題

https://github.com/twin-te/twinte-front/pull/567/files#diff-8bdcc69cbcde246347d14c3f1ac6b925b9cedeb7d09cf880b411f2118bb85e16L399-L405 の変更で検索イベントの収集コードが抜け落ちた。

これにより 2022/10 月ごろからデータが一切取れない状況が続いている。

## 解決策

検索イベントの収集コードを再度挿入する。

**Comment by HosokawaR** [comment]
この処理をどこに挿入したらきれいなのか迷う（`usecase/course/searchCourse`だと責務が広すぎる）ので、今のアーキテクチャを組み立てた @hayato24s にお願いしたい。

**Comment by hayato24s** [comment]
@HosokawaR 

該当箇所は[ここ](https://github.com/twin-te/twinte-front/blob/c832def3ba7e31749a7dfaeef7e187f8540100d7/old_src/pages/add/search.vue#L399-L405)であっていますでしょうか？

vueに関連する`useGtm`を使用しているので、uiを記述しているファイルに処理を書けばいいのではないかなと思いました。

**Comment by HosokawaR** [comment]
そこです！

確かに `useGtm` が vue に依存しているので ui 以下に書いてよさそうですね。
