### ISSUE TITLE
検索したら勝手にキーボードが閉じてほしい

### ISSUE THREAD

**Issue by SIY1121** [twin-te/twinte-front#64]
## 概要
授業検索でキーワード入力後、エンターを押したらキーボードは引っ込んでほしい
## 目的
UX向上
## 提案内容
授業検索でキーワード入力後、エンターを押したらキーボードは引っ込んでほしい
## タスク

- [ ] 検索のタイミングで input要素のblur() を呼び出す

**Comment by HikaruEgashira** [comment]
方針
components/def-dialod-add.vue
のinput に@blur="search()" を入れればいいっぽい
明日あたりにする
