### ISSUE TITLE
Web版でCSVを追加する時，一括追加できるように

### ISSUE THREAD

**Issue by qqhann** [twin-te/twinte-front#69]
## 概要
Web版でCSVを追加すると，チェックボックスを一つ一つつけなければ授業を追加できない

## 提案内容
一括追加ボタンを追加する
または，インポートした際チェック済みを初期値とする

## タスク

- [ ] 細かいタスクに分解できているなら書き出す

**Comment by HikaruEgashira** [comment]
@qqhann 実装しました。提案ありがとうございます！
