### ISSUE TITLE
通年の講義が表示されない

### ISSUE THREAD

**Issue by SIY1121** [twin-te/twinte-front#70]
## 概要
通年実施の講義が表示されない
## 再現手順
通年の講義を追加しても時間割に表示されない
## 修正しないとどう困るか
困ります！
## 原因
moduleが通年の講義が無視されている
## 修正案
moduleが通年の講義は全moduleで表示する

**Comment by HikaruEgashira** [comment]
frontで修正できないとおもいます

**Comment by SIY1121** [comment]
モジュール指定しない方法での取得 `https://dev.api.twinte.net/v1/timetables?year=2019` は通年授業も帰ってきてるはずなので、フロントでできると思う

**Comment by HikaruEgashira** [comment]
あ、全部モジュール指定していないつもり

https://github.com/twin-te/twinte-front/blob/master/src/store/api/timetables.ts#L54

**Comment by SIY1121** [comment]
ごめん、言葉足らず。
講義の登録は出来てて、timetable API からも帰って来てるけど、UIに表示されてない。
（moduleでフィルタしてるんだろうけど、そこで通年授業も弾かれてる）

**Comment by HikaruEgashira** [comment]
たしかに
了解です
