### ISSUE TITLE
授業の詳細モーダルの切り替わりが遅い

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#71]
## 概要
授業をタップしたあと、他の授業をタップするとじゃっかん前にタップした授業の詳細が表示される。
また、メモもその授業のものが出てくるまで時間がかかる。
## 再現手順
授業をタップしたあと、他の授業をタップする。
## 修正しないとどう困るか
あれ？？？となります

**Comment by HikaruEgashira** [comment]
API通信があるのでこれを修正するにはローカルストレージで実装するのがいいと思う

**Comment by SIY1121** [comment]
API通信もあるけど
https://github.com/twin-te/twinte-front/blob/ce036f7a8dd92ec839fc93d1f3cffb5f457a8404/src/components/def-dialog-detail.vue#L234-L243

ここの１秒が大きい気がする。

せめて、Loadingを出すなりしないと、ユーザーが混乱しそう。

**Comment by HikaruEgashira** [comment]
ここは自分じゃ実装出来ないです、、
他の人に実装を任せます
