### ISSUE TITLE
シラバスがほとんど見れない

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-front#72]
## 概要
シラバスを見れる授業があまりない。（coinsだけ？？）
## 修正しないとどう困るか
悲しい

**Comment by HikaruEgashira** [comment]
coinsだけだと思うから、元Twin:teと同じコード使う?(Gから始まる授業はcoinsのシラバスを参照する)

**Comment by takonasu** [comment]
GBだとcoins参照でいいと思います
